# Basic
spring.application.name=microservice-template
server.port=8089

# DB Configuration
spring.datasource.url=jdbc:mysql://192.168.1.135:3306/itemsdb?useMysqlMetadata=true
spring.datasource.username=root
spring.datasource.password=rootpass
spring.flyway.enabled=false

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Kafka
spring.kafka.bootstrap-servers=192.168.1.135:9092

# Logging
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.type.descriptor.sql.BasicExtractor=TRACE

# TMDB
tmdb.base-url=https://api.themoviedb.org/3
tmdb.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzZDY3ZGQ4NWQ1ZmM1MzEzODI4MGNhYzc0NjVmMmQyNSIsIm5iZiI6MTc2NDk0MTU5MC44OTIsInN1YiI6IjY5MzJkZjE2YzgzNDQ0YjIwODM2ZTUzMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.DLkNNrhNlL1wwPnEVOkH8s5dBcL_fjOm5rwWxFCj640

# JWT
jwt.secret=DTy+yNw7gf4vKztbyHkRyNQ4qOcdxD49eF0sAXZ6jYw=

## Spring Security detailed debug
#logging.level.org.springframework.security=TRACE
#
## JWT debugging
#logging.level.org.springframework.security.oauth2=DEBUG

# Elasticsearch (repo)
spring.elasticsearch.uris=http://192.168.1.135:9200