INSERT INTO items (id, nombre) VALUES (UUID(), 'Quantum Processor');
INSERT INTO items (id, nombre) VALUES (UUID(), 'HoloLens Mk II');
INSERT INTO items (id, nombre) VALUES (UUID(), 'Raspberry Pi 5');
INSERT INTO items (id, nombre) VALUES (UUID(), 'Neural Interface Headset');
INSERT INTO items (id, nombre) VALUES (UUID(), 'AI-powered Coffee Maker');
INSERT INTO items (id, nombre) VALUES (UUID(), 'Teleportation Module');
INSERT INTO items (id, nombre) VALUES (UUID(), 'Zero-point Energy Battery');
INSERT INTO items (id, nombre) VALUES (UUID(), 'Smart Cyberdeck');
INSERT INTO items (id, nombre) VALUES (UUID(), 'Photon Sword');
INSERT INTO items (id, nombre) VALUES (UUID(), 'Haptic Feedback Gloves');